name: Build, Lint, and Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Check for Build Output
        run: |
          if [[ -d dist ]] && [[ $(ls dist | wc -l) -gt 0 ]]; then
            echo "Build output found."
          else
            echo "No build output found. Build might have failed."
            exit 1
          fi
  lint-and-format:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier Formatting
        run: npm run prettier
